
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  database: fileupload_development
test:
  <<: *default
  database: fileupload_test
