# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a69d024a0a6ba02e665882bc17bf03213445cf794ad8ea086b5b7f2e33dae40ea05b0b8e7a1914601996212390066b7bdfbb5c2b6838cef98c5e67dd482de6a

test:
  secret_key_base: f2af3b6d3721e6f45b9ad102ef64479955eadbbc3e2476911a9f5eef7cf7b569c9c21bda99ea9096e103ffff293ef26a1b7ca8afcb14014ea2fdc7565520db66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
